# Generated by Django 2.2.8 on 2021-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210423_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='aboutus',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='contact',
            new_name='myname',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='references',
        ),
        migrations.AddField(
            model_name='setting',
            name='my_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='my_sapo',
            field=models.CharField(default=0, max_length=450),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='create_at',
            field=models.DateTimeField(),
        ),
    ]
