# Generated by Django 2.2.8 on 2021-04-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210423_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='my_sapo',
            field=models.TextField(),
        ),
    ]
