# Generated by Django 2.2.8 on 2021-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='message',
            new_name='messages',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, help_text='Some help text', max_length=50),
        ),
    ]
