# Generated by Django 2.2.8 on 2021-04-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210423_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='icon_me',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Some help text', max_length=50),
        ),
    ]
