# Generated by Django 2.2.8 on 2021-04-24 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210424_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='set',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Setting'),
            preserve_default=False,
        ),
    ]
