# Generated by Django 2.2.8 on 2021-04-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactmessage_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='set',
        ),
    ]
