# Generated by Django 2.2.8 on 2021-04-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_blog_catalogproview_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productview',
            name='image',
            field=models.ImageField(upload_to='images/home'),
        ),
        migrations.AlterField(
            model_name='productview',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
