# Generated by Django 2.2.8 on 2021-04-25 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210425_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
