# Generated by Django 2.2.8 on 2021-04-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210425_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
