# Generated by Django 2.2.8 on 2021-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210425_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sapo', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.BooleanField(),
        ),
    ]
