# Generated by Django 2.2.8 on 2021-04-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210425_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='color',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
